version: '3'
services:

  openjdk:
    image: openjdk:17
    container_name: openjdk
    command: tail -f /dev/null # keep container running/alive

  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: ${POSTGRES_CONTAINER_NAME}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: